name: KoliBri Documentation Report
description: Create a report for KoliBri documentation / Einen Bericht für die KoliBri-Dokumentation erstellen
title: '📖 Docs: '
labels: ['doc']
body:
  - type: textarea
    id: update
    attributes:
      label: What is the update you wish to see? / Welche Aktualisierung würden Sie gerne sehen?
      description: |
        Example: I would like to fix an example using the `<Link>` component. Or, the `<Link>` component docs are missing information.

        ```diff
        # Beispiel: Ich möchte ein Beispiel für die Verwendung der `<Link>`-Komponente korrigieren. Oder in der Dokumentation der Komponente `<Link>` fehlen Informationen.
        ````
    validations:
      required: true
  - type: textarea
    id: context
    attributes:
      label: Is there any context that might help us understand? / Gibt es irgendeinen Zusammenhang, der uns helfen könnte, es besser zu verstehen? 
      description: |
        A clear description of any added context that might help us understand.

        ```diff
        # Eine klare Beschreibung jedes zusätzlichen Kontextes, der zum Verständnis beitragen könnte.
        ````
    validations:
      required: true
  - type: input
    id: link
    attributes:
      label: Does the docs page already exist? Please link to it. / Gibt es die Doku-Seite bereits? Bitte verlinken Sie sie.
      description: 'Example: https://public-ui.github.io/docs/components/abbr'
    validations:
      required: false