name: Report a documentation issue
description: Create a report for KoliBri documentation
title: '📖 Docs: '
labels: ['doc']
body:
  - type: textarea
    id: update
    attributes:
      label: What is the update you wish to see?
      description: |
        Example: I would like to fix an example using the `<Link>` component. Or, the `<Link>` component docs are missing information.
    validations:
      required: true
  - type: textarea
    id: context
    attributes:
      label: Is there any context that might help us understand?
      description: |
        A clear description of any added context that might help us understand.
    validations:
      required: true
  - type: input
    id: link
    attributes:
      label: Does the docs page already exist? Please link to it.
      description: 'Example: https://public-ui.github.io/docs/components/abbr'
    validations:
      required: false