name: Auto dependency updater

on:
  schedule:
    - cron: '0 2 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Update dependencies
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          persist-credentials: false
          ref: 'main'
      - uses: pnpm/action-setup@v2.2.4
        with:
          version: 7
      - uses: actions/setup-node@v3
        with:
          cache: pnpm
          node-version: 16
      #- uses: actions/cache@v3
      #  env:
      #    cache-name: cache-pnpm-modules
      #  with:
          # pnpm cache files are stored in `~/.pnpm-store` on Linux/macOS
      #    path: ~/.pnpm-store
      #    key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ matrix.node-version }}
      #    restore-keys: |
      #      {{ runner.os }}-pnpm
      - name: Create new branch
        run: git checkout -b chore/auto-update-deps
      - name: Install tools
        run: npm i lerna npm-check-updates --no-save
      - name: Update dependencies
        run: npm run update
      - name: Reinstall dependencies
        run: npm run reinstall
      - name: Commit changed files
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add **/package.json **/pnpm-lock.yaml
          git status
          git commit -m "chore: auto dependency update"
      - uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: 'chore/auto-update-deps'
          force: true
