name: Publish

env:
  access: public
  github-registry: https://npm.pkg.github.com
  github-token: ${{ secrets.GITHUB_TOKEN }}
  npmjs-registry: https://registry.npmjs.org
  npmjs-token: ${{ secrets.NPMJS_TOKEN }}
  npmjs-tag: next

on:
  workflow_dispatch:

jobs:
  publish:
    if: github.repository == 'public-ui/kolibri'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: false

      # - uses: pnpm/action-setup@v2.2.4
      #   with:
      #     run_install: false
      #     version: 7
      # - uses: actions/setup-node@v3
      #   with:
      #     cache: pnpm
      #     node-version: 16

      # https://github.com/pnpm/action-setup#use-cache-to-reduce-installation-time
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          # cache: pnpm
          node-version: 18
      - name: Install pnpm
        uses: pnpm/action-setup@v2
        id: pnpm-install
        with:
          version: 8
          run_install: false
      - name: Get pnpm store directory
        id: pnpm-cache
        shell: bash
        run: echo "STORE_PATH=$(pnpm store path)" >> $GITHUB_OUTPUT
      - uses: actions/cache@v3
        name: Setup pnpm cache
        with:
          path: ${{ steps.pnpm-cache.outputs.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store
          restore-keys: |
            ${{ runner.os }}-pnpm-store

      - name: Install
        run: pnpm i --no-frozen-lockfile

      - name: Build
        run: pnpm -r build

      - name: Build and publish schema
        run: npm publish --access ${{env.access}} --tag ${{env.npmjs-tag}} || true
        working-directory: packages/schema
        env:
          NODE_AUTH_TOKEN: ${{env.npmjs-token}}
      - name: Build and publish components
        run: npm publish --access ${{env.access}} --tag ${{env.npmjs-tag}} || true
        working-directory: packages/components
        env:
          NODE_AUTH_TOKEN: ${{env.npmjs-token}}
      - name: Build and publish adapter angular v11
        run: npm publish --access ${{env.access}} --tag ${{env.npmjs-tag}} || true
        working-directory: packages/adapters/angular/v11
        env:
          NODE_AUTH_TOKEN: ${{env.npmjs-token}}
      - name: Build and publish adapter angular v12
        run: npm publish --access ${{env.access}} --tag ${{env.npmjs-tag}} || true
        working-directory: packages/adapters/angular/v12
        env:
          NODE_AUTH_TOKEN: ${{env.npmjs-token}}
      - name: Build and publish adapter angular v13
        run: npm publish --access ${{env.access}} --tag ${{env.npmjs-tag}} || true
        working-directory: packages/adapters/angular/v13
        env:
          NODE_AUTH_TOKEN: ${{env.npmjs-token}}
      - name: Build and publish adapter angular v14
        run: npm publish --access ${{env.access}} --tag ${{env.npmjs-tag}} || true
        working-directory: packages/adapters/angular/v14
        env:
          NODE_AUTH_TOKEN: ${{env.npmjs-token}}
      - name: Build and publish adapter angular v15
        run: npm publish --access ${{env.access}} --tag ${{env.npmjs-tag}} || true
        working-directory: packages/adapters/angular/v15
        env:
          NODE_AUTH_TOKEN: ${{env.npmjs-token}}
      - name: Build and publish adapter angular v16
        run: npm publish --access ${{env.access}} --tag ${{env.npmjs-tag}} || true
        working-directory: packages/adapters/angular/v16
        env:
          NODE_AUTH_TOKEN: ${{env.npmjs-token}}
      - name: Build and publish adapter react
        run: npm publish --access ${{env.access}} --tag ${{env.npmjs-tag}} || true
        working-directory: packages/adapters/react
        env:
          NODE_AUTH_TOKEN: ${{env.npmjs-token}}
      - name: Build and publish adapter react-standalone
        run: npm publish --access ${{env.access}} --tag ${{env.npmjs-tag}} || true
        working-directory: packages/adapters/react-standalone
        env:
          NODE_AUTH_TOKEN: ${{env.npmjs-token}}
      - name: Build and publish adapter solid
        run: npm publish --access ${{env.access}} --tag ${{env.npmjs-tag}} || true
        working-directory: packages/adapters/solid
        env:
          NODE_AUTH_TOKEN: ${{env.npmjs-token}}
      - name: Build and publish adapter vue
        run: npm publish --access ${{env.access}} --tag ${{env.npmjs-tag}} || true
        working-directory: packages/adapters/vue
        env:
          NODE_AUTH_TOKEN: ${{env.npmjs-token}}
      - name: Build and publish adapter preact
        run: npm publish --access ${{env.access}} --tag ${{env.npmjs-tag}} || true
        working-directory: packages/adapters/preact
        env:
          NODE_AUTH_TOKEN: ${{env.npmjs-token}}
      - name: Build and publish adapter hydrate
        run: npm publish --access ${{env.access}} --tag ${{env.npmjs-tag}} || true
        working-directory: packages/adapters/hydrate
        env:
          NODE_AUTH_TOKEN: ${{env.npmjs-token}}
      - name: Build and publish create-kolibri
        run: npm publish --access ${{env.access}} --tag ${{env.npmjs-tag}} || true
        working-directory: packages/create-kolibri
        env:
          NODE_AUTH_TOKEN: ${{env.npmjs-token}}
      - name: Build and publish tools kolibri-cli
        run: npm publish --access ${{env.access}} --tag ${{env.npmjs-tag}} || true
        working-directory: packages/tools/kolibri-cli
        env:
          NODE_AUTH_TOKEN: ${{env.npmjs-token}}
      - name: Build and publish themes
        run: npm publish --access ${{env.access}} --tag ${{env.npmjs-tag}} || true
        working-directory: packages/themes
        env:
          NODE_AUTH_TOKEN: ${{env.npmjs-token}}
      - name: Build and publish sample react
        run: npm publish --access ${{env.access}} --tag ${{env.npmjs-tag}} || true
        working-directory: packages/samples/react
        env:
          NODE_AUTH_TOKEN: ${{env.npmjs-token}}
      - name: Build and publish tools visual-tests
        run: npm publish --access ${{env.access}} --tag ${{env.npmjs-tag}} || true
        working-directory: packages/tools/visual-tests
        env:
          NODE_AUTH_TOKEN: ${{env.npmjs-token}}

      # deprecated packages
      - name: Build and publish core
        run: npm publish --access ${{env.access}} --tag ${{env.npmjs-tag}} || true
        working-directory: packages/core
        env:
          NODE_AUTH_TOKEN: ${{env.npmjs-token}}

  publish-page:
    needs: publish
    uses: public-ui/kolibri/.github/workflows/publish-page.yml@develop
